import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Jules',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'Boris',
            email: 'boris@example.com',
            password: bcrypt.hashSync('12345', 8),
            isAdmin: false,
        },
    ],
    products:[
        {
            name:'Bud bud',
            category:'herb',
            image:'/images/p1.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {          
            name:'Bod bod',
            category:'herb',
            image:'/images/p2.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {           
            name:'Bid bid',
            category:'herb',
            image:'/images/p3.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {            
            name:'Bad bad',
            category:'herb',
            image:'/images/p1.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {        
            name:'Bud bad',
            category:'herb',
            image:'/images/p2.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {
            name:'Bad bud',
            category:'herb',
            image:'/images/p3.jpg',
            price: 10,
            countInStock: 0,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },

    ],
};
export default data;