const data = {
    products:[
        {
            _id:'1',
            name:'Bud bud',
            category:'herb',
            image:'/images/p1.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {
            _id:'2',
            name:'Bud bud',
            category:'herb',
            image:'/images/p2.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {
            _id:'3',
            name:'Bud bud',
            category:'herb',
            image:'/images/p3.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {
            _id:'4',
            name:'Bud bud',
            category:'herb',
            image:'/images/p1.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {
            _id:'5',
            name:'Bud bud',
            category:'herb',
            image:'/images/p2.jpg',
            price: 10,
            countInStock: 10,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },
        {
            _id:'6',
            name:'Bud bud',
            category:'herb',
            image:'/images/p3.jpg',
            price: 10,
            countInStock: 0,
            brand: 'Gorilla glue',
            rating: 4.5,
            numReviews: 10,
            description: 'grosse beuh',
        },

    ],
};
export default data;